export const images = [
  {
    id: 1,
    src: "/bento_grid/render_6.png",
    alt: "Aluminium Case",
    col_size: "large",
    content1: "Full aluminum case.",
    content2: "Premium materials for satisfying heft and durability.",
  },
  {
    id: 2,
    src: "/bento_grid/render_5.png",
    alt: "Interchangeable knob system",
    col_size: "small",
    content1: "Interchangeable knob system.",
    content2: "Customize your control dial to click, scroll, or press.",
  },
  {
    id: 3,
    src: "/bento_grid/render_2.png",
    alt: "Cross Platform",
    col_size: "medium",
    content1: "Cross Platform.",
    content2: "Mac, Windows, or Linux, Nimbus adapts to your workflow.",
  },
  {
    id: 4,
    src: "/bento_grid/render_9.png",
    alt: "Hot-Swappable Switches",
    col_size: "medium",
    content1: "Hot-Swappable Switches.",
    content2: "Change your feel without any soldering.",
  },
  {
    id: 5,
    src: "/bento_grid/render_11.png",
    alt: "Custom Nimbus Keycap Profile",
    col_size: "small",
    content1: "Custom Nimbus Keycap Profile.",
    content2: "Designed for long coding sessions.",
  },
  {
    id: 6,
    src: "/bento_grid/render_3.png",
    alt: "E-Ink Display Screen",
    col_size: "large",
    content1: "E-Ink Display Screen.",
    content2: "Show battery, status, or a custom design.",
  },
];
